version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "micro"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "adminadmin"
    ports:
      - "5432:5432"